#!/usr/bin/env python3
"""
download_pages.py
------------------
Downloads all 604 pages of the Madinah Mushaf (Uthmani script, King Fahd
Quran Complex fonts) as PNG images and saves them locally as:

    pages/page001.png
    pages/page002.png
    ...
    pages/page604.png

so that index.html can load them from a same-origin, CORS-free local folder.

Source
------
Images are pulled from the "Quran-PNG" GitHub repository
(https://github.com/GovarJabbar/Quran-PNG, mirrored from the Govar-Web/Quran-PNG
org repo), which commits each Madinah Mushaf page (generated by the
quran/quran.com-images project, King Fahd Quran Complex fonts) as an
individual PNG file (001.png ... 604.png) at the repo root. Files are served
straight from raw.githubusercontent.com, which sends permissive CORS headers
and is safe to hot-link from a local page. Two more GitHub-hosted mirrors are
tried automatically as fallbacks if a page is missing from the primary one.

Usage
-----
    pip install requests
    python download_pages.py

Optional flags:
    python download_pages.py --start 1 --end 604   # download a sub-range
    python download_pages.py --workers 8            # parallel downloads
    python download_pages.py --retries 5             # retry attempts per page
    python download_pages.py --out ./pages           # output folder

The script is resumable: pages that already exist locally (and are not
zero-byte / corrupt) are skipped automatically, so you can re-run it after
a network hiccup and it will only fetch what's missing.
"""

import argparse
import concurrent.futures
import os
import sys
import time
import urllib.request
import urllib.error

# Primary source: each page committed as its own PNG at the repo root,
# served via GitHub's raw CDN (CORS-friendly, no API key required).
PRIMARY_URL_TEMPLATE = (
    "https://raw.githubusercontent.com/GovarJabbar/Quran-PNG/"
    "master/{page:03d}.png"
)

# Fallback 1: the upstream org repo the above is mirrored from.
FALLBACK_URL_TEMPLATE_1 = (
    "https://raw.githubusercontent.com/Govar-Web/Quran-PNG/"
    "master/{page:03d}.png"
)

# Fallback 2: jsDelivr fronting the same repo (also CORS-open), useful if
# raw.githubusercontent.com is rate-limited or briefly unreachable.
FALLBACK_URL_TEMPLATE_2 = (
    "https://cdn.jsdelivr.net/gh/GovarJabbar/Quran-PNG@master/"
    "{page:03d}.png"
)

# Fallback 3: an older, differently-named mirror (1024px wide scans) kept as
# a last resort in case the repos above ever disappear or get renamed.
FALLBACK_URL_TEMPLATE_3 = (
    "https://raw.githubusercontent.com/tarekeldeeb/madina_images/"
    "w1024/w1024_page{page:03d}.png"
)

TOTAL_PAGES = 604
USER_AGENT = "Mozilla/5.0 (compatible; MushafPageDownloader/1.0)"
MIN_VALID_BYTES = 1024  # anything smaller than this is treated as a failed/corrupt download


def download_one(page_num: int, out_dir: str, retries: int, timeout: int) -> tuple:
    """Download a single page image. Returns (page_num, ok, message)."""
    filename = f"page{page_num:03d}.png"
    dest_path = os.path.join(out_dir, filename)

    # Skip already-downloaded, valid files (resumable behaviour).
    if os.path.exists(dest_path) and os.path.getsize(dest_path) >= MIN_VALID_BYTES:
        return page_num, True, "already exists, skipped"

    urls = [
        PRIMARY_URL_TEMPLATE.format(page=page_num),
        FALLBACK_URL_TEMPLATE_1.format(page=page_num),
        FALLBACK_URL_TEMPLATE_2.format(page=page_num),
        FALLBACK_URL_TEMPLATE_3.format(page=page_num),
    ]

    last_error = None
    for url in urls:
        for attempt in range(1, retries + 1):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
                with urllib.request.urlopen(req, timeout=timeout) as resp:
                    data = resp.read()

                if len(data) < MIN_VALID_BYTES:
                    raise ValueError(f"downloaded file too small ({len(data)} bytes)")

                tmp_path = dest_path + ".part"
                with open(tmp_path, "wb") as f:
                    f.write(data)
                os.replace(tmp_path, dest_path)
                return page_num, True, f"downloaded from {url}"

            except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, ValueError, OSError) as e:
                last_error = e
                time.sleep(min(2 ** attempt, 8))  # exponential backoff, capped

    return page_num, False, f"FAILED after retries: {last_error}"


def main():
    parser = argparse.ArgumentParser(description="Download Madinah Mushaf page images.")
    parser.add_argument("--start", type=int, default=1, help="first page number (default 1)")
    parser.add_argument("--end", type=int, default=TOTAL_PAGES, help="last page number (default 604)")
    parser.add_argument("--out", type=str, default="pages", help="output folder (default ./pages)")
    parser.add_argument("--workers", type=int, default=6, help="parallel download workers (default 6)")
    parser.add_argument("--retries", type=int, default=4, help="retry attempts per URL (default 4)")
    parser.add_argument("--timeout", type=int, default=20, help="per-request timeout in seconds (default 20)")
    args = parser.parse_args()

    if args.start < 1 or args.end > TOTAL_PAGES or args.start > args.end:
        print(f"Error: start/end must be within 1..{TOTAL_PAGES}", file=sys.stderr)
        sys.exit(1)

    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)

    page_numbers = list(range(args.start, args.end + 1))
    total = len(page_numbers)
    print(f"Downloading {total} page(s) into: {out_dir}")
    print("Source: raw.githubusercontent.com/GovarJabbar/Quran-PNG (3 automatic fallback mirrors)\n")

    completed = 0
    failed_pages = []
    start_time = time.time()

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(download_one, p, out_dir, args.retries, args.timeout): p
            for p in page_numbers
        }
        for future in concurrent.futures.as_completed(futures):
            page_num, ok, message = future.result()
            completed += 1
            status = "OK  " if ok else "FAIL"
            print(f"[{completed:>3}/{total}] page {page_num:03d}: {status} - {message}")
            if not ok:
                failed_pages.append(page_num)

    elapsed = time.time() - start_time
    print(f"\nDone in {elapsed:.1f}s. {total - len(failed_pages)}/{total} pages saved to {out_dir}")

    if failed_pages:
        print(f"\n{len(failed_pages)} page(s) failed: {failed_pages}")
        print("Re-run this script to retry just the missing ones (already-downloaded pages are skipped).")
        print("If failures persist, check your internet connection or firewall, or open an issue")
        print("against https://github.com/tarekeldeeb/madina_images to confirm the source is reachable.")
        sys.exit(2)
    else:
        print("All pages downloaded successfully. You can now open index.html.")


if __name__ == "__main__":
    main()
